- name: Install PHP Remi Repository
  yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm update_cache=yes state=latest
 
- name: Enable PHP Remi Repository
  command: yum install yum-utils
  command: yum-config-manager --enable remi-php74
  #command: dnf module reset php -y
  #command: dnf module enable php:remi-7.4 -y
 
- name: Install PHP Extensions
  yum: name={{ item }} update_cache=yes state=latest
  loop: "{{ php_modules }}"

