---
- name: Check et Reboot 
  hosts: worker-node2
  remote_user: root 
  tasks:
  - name: create file1  
    file:
       path: /tmp/file1.txt
       state: touch

  - name: test 
    stat:
        path: /tmp/file1.txt
    register: __file_exist

  - name: lancement de reboot avec module reboot 
    reboot:
      msg: "Reboot via ansible"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 30
      post_reboot_delay: 30
      test_command: uptime
    when: __file_exist.stat.exists

  - name: create file2  
    file:
      path: /tmp/file2.txt
      state: touch
